name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/'
      - name: Deploy
        if: github.ref == 'refs/heads/main' # default branch
        uses: actions/deploy-pages@v2